### ISSUE TITLE
BeGet not building on 64 bit

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BeGet#14]
After uncommenting !x86_64 in BeGet recipe:
```
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HWindow.cpp: In member function 'void HWindow::Watch()':
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HWindow.cpp:186:78: error: no matching function for call to 'BMessage::FindData(const char [11], <anonymous enum>, int, const void**, int32*)'
    if (clip->FindData("text/plain", B_MIME_TYPE, 0, (const void**)&text, &len) == B_OK) {
                                                                              ^
In file included from /boot/system/develop/headers/os/support/Archivable.h:10:0,
                 from /boot/system/develop/headers/os/app/Handler.h:12,
                 from /boot/system/develop/headers/os/app/Looper.h:13,
                 from /boot/system/develop/headers/os/interface/Window.h:9,
                 from /sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HWindow.h:4,
                 from /sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HWindow.cpp:1:
/boot/system/develop/headers/os/app/Message.h:269:15: note: candidate: status_t BMessage::FindData(const char*, type_code, const void**, ssize_t*) const
    status_t   FindData(const char* name, type_code type,
               ^
/boot/system/develop/headers/os/app/Message.h:269:15: note:   candidate expects 4 arguments, 5 provided
/boot/system/develop/headers/os/app/Message.h:271:15: note: candidate: status_t BMessage::FindData(const char*, type_code, int32, const void**, ssize_t*) const
    status_t   FindData(const char* name, type_code type,
               ^
/boot/system/develop/headers/os/app/Message.h:271:15: note:   no known conversion for argument 5 from 'int32* {aka int*}' to 'ssize_t* {aka long int*}'
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HWindow.cpp: In member function 'void HWindow::Pulse()':
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HWindow.cpp:465:35: error: lvalue required as unary '&' operand
    fLogView->Insert(&log[ old_len ]);
                                   ^
src/CMakeFiles/BeGet.dir/build.make:350: recipe for target 'src/CMakeFiles/BeGet.dir/HWindow.cpp.o' failed
make[2]: *** [src/CMakeFiles/BeGet.dir/HWindow.cpp.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'src/CMakeFiles/BeGet.dir/all' failed
make[1]: *** [src/CMakeFiles/BeGet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
[Errno -2147459069] No such file or directory: '/boot/home/haikuports/haiku-apps/beget/work-1.2.3'
Error: Build has failed - stopping.

```

**Comment by Vidrep** [comment]
Below is my latest attempt at building on 64 bit, with debug enabled:

```
Welcome to the Haiku shell.
~/haikuports> haikuporter -S -j4 --get-dependencies --no-source-packages --debug beget
Checking if any package-infos need to be updated ...
        updating dependency infos of beget-1.2.3
Looking for stale dependency-infos ...
Checking if package dependencies need to be updated ...
        updating dependency infos of beget-1.2.3
----------------------------------------------------------------------
haiku-apps::beget-1.2.3
        /boot/home/haikuports/haiku-apps/beget/beget-1.2.3.recipe
----------------------------------------------------------------------

Downloading: https://github.com/HaikuArchives/BeGet/archive/a170b0e6860c76599ab202a1532088cfcec447ad.tar.gz ...
--2017-07-17 17:23:44--  https://github.com/HaikuArchives/BeGet/archive/a170b0e6860c76599ab202a1532088cfcec447ad.tar.gz
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/HaikuArchives/BeGet/tar.gz/a170b0e6860c76599ab202a1532088cfcec447ad [following]
--2017-07-17 17:23:45--  https://codeload.github.com/HaikuArchives/BeGet/tar.gz/a170b0e6860c76599ab202a1532088cfcec447ad
Resolving codeload.github.com... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/boot/home/haikuports/haiku-apps/beget/download/a170b0e6860c76599ab202a1532088cfcec447ad.tar.gz’
     0K .......... .......... .......... .......... ..........  312K
    50K .......... .......... .......... .......... ..........  636K
   100K .......... .......... .......... .......... .......... 5.74M
   150K .......... .......... .......... .......... ..........  643K
   200K .......... .......... .......... .......... ..........  642K
   250K .......... .                                           5.68M=0.4s
2017-07-17 17:23:46 (645 KB/s) - ‘/boot/home/haikuports/haiku-apps/beget/download/a170b0e6860c76599ab202a1532088cfcec447ad.tar.gz’ saved [267296]
Validating checksum of a170b0e6860c76599ab202a1532088cfcec447ad.tar.gz
Unpacking source of a170b0e6860c76599ab202a1532088cfcec447ad.tar.gz
Initialized empty Git repository in /boot/home/haikuports/haiku-apps/beget/work-1.2.3/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/.git/
Fetching package for cmd:cmake ...
chroot has these packages active:
        /boot/system/packages/bash-4.4.012-3-x86_64.hpkg
        /boot/system/packages/binutils-2.26.1_2016_07_22-4-x86_64.hpkg
        /boot/system/packages/bzip2-1.0.6-6-x86_64.hpkg
        /boot/system/packages/ca_root_certificates-2017_01_18-1-any.hpkg
        /boot/system/packages/cmake-3.8.2-1-x86_64.hpkg
        /boot/system/packages/coreutils-8.26-3-x86_64.hpkg
        /boot/system/packages/curl-7.54.0-1-x86_64.hpkg
        /boot/system/packages/expat-2.2.1-2-x86_64.hpkg
        /boot/system/packages/ffmpeg-3.3.2-1-x86_64.hpkg
        /boot/system/packages/fontconfig-2.12.1-3-x86_64.hpkg
        /boot/system/packages/freetype-2.8-2-x86_64.hpkg
        /boot/system/packages/gcc-5.4.0_2016_06_04-5-x86_64.hpkg
        /boot/system/packages/gcc_syslibs-5.4.0_2016_06_04-5-x86_64.hpkg
        /boot/system/packages/gettext_libintl-0.19.8.1-4-x86_64.hpkg
        /boot/system/packages/giflib-5.1.2-3-x86_64.hpkg
        /boot/system/packages/gmp-6.1.2-2-x86_64.hpkg
        /boot/system/packages/grep-3.0-3-x86_64.hpkg
        /boot/system/packages/gutenprint-5.2.12-3-x86_64.hpkg
        /boot/system/packages/gzip-1.8-2-x86_64.hpkg
        /boot/system/packages/haiku-r1~alpha4_pm_hrev51289-1-x86_64.hpkg
        /boot/system/packages/haiku_devel-r1~alpha4_pm_hrev51289-1-x86_64.hpkg
        /boot/system/packages/icu-57.1-2-x86_64.hpkg
        /boot/system/packages/jasper-2.0.13-1-x86_64.hpkg
        /boot/system/packages/jasper1-1.900.5-1-x86_64.hpkg
        /boot/system/packages/jpeg-9b-5-x86_64.hpkg
        /boot/system/packages/libicns-0.8.1-6-x86_64.hpkg
        /boot/system/packages/libiconv-1.13.1-9-x86_64.hpkg
        /boot/system/packages/libmodplug-0.8.9.0-1-x86_64.hpkg
        /boot/system/packages/libogg-1.3.2-4-x86_64.hpkg
        /boot/system/packages/libpng16-1.6.29-2-x86_64.hpkg
        /boot/system/packages/libsolv-0.3.0_haiku_2014_12_22-2-x86_64.hpkg
        /boot/system/packages/libtheora-1.1.1-6-x86_64.hpkg
        /boot/system/packages/libvorbis-1.3.5-4-x86_64.hpkg
        /boot/system/packages/libvpx3-1.5.0-2-x86_64.hpkg
        /boot/system/packages/libwebp-0.6.0-2-x86_64.hpkg
        /boot/system/packages/libxml2-2.9.3-5-x86_64.hpkg
        /boot/system/packages/llvm_libs-4.0.1-1-x86_64.hpkg
        /boot/system/packages/make-4.1-2-x86_64.hpkg
        /boot/system/packages/mesa-17.1.4-1-x86_64.hpkg
        /boot/system/packages/mpc-1.0.3-3-x86_64.hpkg
        /boot/system/packages/mpfr-3.1.5-1-x86_64.hpkg
        /boot/system/packages/ncurses6-6.0-3-x86_64.hpkg
        /boot/system/packages/noto-20170202-7-any.hpkg
        /boot/system/packages/noto_sans_cjk_jp-1.004-2-any.hpkg
        /boot/system/packages/openssl-1.0.2l-1-x86_64.hpkg
        /boot/system/packages/qrencode-3.4.4-3-x86_64.hpkg
        /boot/system/packages/readline-7.0-3-x86_64.hpkg
        /boot/system/packages/sed-4.4-2-x86_64.hpkg
        /boot/system/packages/speex-1.2.0-2-x86_64.hpkg
        /boot/system/packages/tar-1.29-3-x86_64.hpkg
        /boot/system/packages/tiff4-4.0.8-2-x86_64.hpkg
        /boot/system/packages/unzip-6.0-4-x86_64.hpkg
        /boot/system/packages/zlib-1.2.11-3-x86_64.hpkg
----- Package Info ----------------
header size:                     80
heap size:                      706
TOC size:                        41
package attributes size:        744
total size:                     786
-----------------------------------
waiting for build package beget-1.2.3-4 to be activated
Building ...
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeModules/UseHaiku.cmake:51 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "BeGet".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  CMakeModules/UseHaiku.cmake:28 (haiku_add_resource_internal)
  src/CMakeLists.txt:22 (haiku_add_resource_def)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeModules/UseHaiku.cmake:84 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "BeGet".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  src/CMakeLists.txt:25 (haiku_auto_mimetype)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad
Scanning dependencies of target BeGet.rsrc
[  5%] Compiling resource /sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/CMakeFiles/BeGet.rsrc.dir/BeGet.rsrc
[  5%] Built target BeGet.rsrc
Scanning dependencies of target BeGet_check_resources
[  5%] Built target BeGet_check_resources
Scanning dependencies of target BeGet
[ 10%] Building CXX object src/CMakeFiles/BeGet.dir/HApp.cpp.o
[ 15%] Building CXX object src/CMakeFiles/BeGet.dir/HBeGetSettingView.cpp.o
[ 20%] Building CXX object src/CMakeFiles/BeGet.dir/HCaption.cpp.o
[ 25%] Building CXX object src/CMakeFiles/BeGet.dir/HListItem.cpp.o
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp: In member function 'void HListItem::SetReceivedSize(uint32)':
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp:262:24: error: invalid initialization of non-const reference of type 'time_t& {aka long int&}' from an rvalue of type 'time_t {aka long int}'
   FormatTime(rtime, str);
                        ^
In file included from /sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp:1:0:
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.h:70:7: note:   initializing argument 1 of 'void HListItem::FormatTime(time_t&, BString&)'
  void FormatTime(time_t& t , BString& out);
       ^
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp: In member function 'uint32 HListItem::ConvertWgetSize(char*)':
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp:628:20: warning: operation on 'p' may be undefined [-Wsequence-point]
     *p++ = *(p + 1);
                    ^
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp: In member function 'void HListItem::FormatTime(time_t&, BString&)':
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp:716:52: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int32 {aka int}' [-Wformat=]
  ::sprintf(buf, "%.2ld:%.2ld:%.2ld", hour, min, sec);
                                                    ^
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp:716:52: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'int32 {aka int}' [-Wformat=]
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp:716:52: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'int32 {aka int}' [-Wformat=]
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp:716:52: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int32 {aka int}' [-Wformat=]
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp:716:52: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'int32 {aka int}' [-Wformat=]
/sources/BeGet-a170b0e6860c76599ab202a1532088cfcec447ad/src/HListItem.cpp:716:52: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'int32 {aka int}' [-Wformat=]
src/CMakeFiles/BeGet.dir/build.make:134: recipe for target 'src/CMakeFiles/BeGet.dir/HListItem.cpp.o' failed
make[2]: *** [src/CMakeFiles/BeGet.dir/HListItem.cpp.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'src/CMakeFiles/BeGet.dir/all' failed
make[1]: *** [src/CMakeFiles/BeGet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1219, in _executeInChroot
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 773, in taskFunction
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1295, in _executeBuild
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1380, in _doBuildStage
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1489, in _doRecipeAction
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1524, in _openShell
  File "/packages/python-2.7.13-3/.self/lib/python2.7/subprocess.py", line 186, in check_call
CalledProcessError: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 39, in __init__
    self.run(args)
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 403, in run
    self._buildPort(port, True, self.packagesPath)
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 626, in _buildPort
    port.build(self.packagesPath, self.options.package, targetPath)
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 789, in build
    self._executeInChroot(chrootSetup, makeChrootFunctions())
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1235, in _executeInChroot
    chrootFunctions['failure']()
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 780, in failureFunction
    sysExit(u'Build has failed - stopping.')
  File "/boot/home/haikuporter/HaikuPorter/Utils.py", line 66, in sysExit
    sys.exit(message.encode('utf-8'))
SystemExit: Error: Build has failed - stopping.
~/haikuports> 

```

**Comment by korli** [comment]
this project uses static binary libs, this is just impossible to build on x86_64, unless these dependency libs are removes, ie libs/liblocale/liblocale.a
